name: Q2 Workflow

on: [push]

permissions:
  contents: write

jobs:
  archive-toto:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Définir la date et heure d'exécution
      id: vars
      run: echo "RUN_DATE=$(date -d '+2 hour' '+%d/%m/%Y %H:%M:%S')" >> $GITHUB_ENV

    - name: Créer Q2_archive_TOTO.txt avec infos et contenu
      run: |
        echo "Nom et prénom : Remi Viez" > Q2_archive_TOTO.txt
        echo "Date d'exécution : $RUN_DATE" >> Q2_archive_TOTO.txt
        echo "" >> Q2_archive_TOTO.txt
        echo "Contenu de TOTO.txt :" >> Q2_archive_TOTO.txt
        cat TOTO.txt >> Q2_archive_TOTO.txt
        echo "" >> Q2_archive_TOTO.txt
        echo "Taille du fichier TOTO.txt :" >> Q2_archive_TOTO.txt
        wc -l TOTO.txt >> Q2_archive_TOTO.txt
        wc -m TOTO.txt >> Q2_archive_TOTO.txt

    - name: Commit et push du fichier Q2_archive_TOTO.txt
      run: |
        git config user.name "RemiViez"
        git config user.email "remi.viez@etu.univ-lehavre.fr"
        git add Q2_archive_TOTO.txt
        git commit -m "Ajout de Q2_archive_TOTO.txt avec infos supplémentaires" || echo "Rien à commit"
        git push
